apiVersion: v1
kind: Pod
metadata:
  name: backend-user
  namespace: udagram-api-user
spec:
  containers:
  - name: udagram-api-user
    image: okoth/udagram-api-user:v2
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]